const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const read = (file) => fs.readFileSync(path.join(ROOT, file), 'utf8');
const requireText = (text, needle, label) => {
  if (!text.includes(needle)) throw new Error(`Contrat Missions manquant: ${label} (${needle})`);
};
const forbidText = (text, needle, label) => {
  if (text.includes(needle)) throw new Error(`Contrat Missions violé: ${label} (${needle})`);
};

const constants = read('database/constants.js');
const migrations = read('database/migrations/index.js');
const migration40 = read('database/migrations/040_missions_core.js');
const migration41 = read('database/migrations/041_missions_architecture.js');
const migration42 = read('database/migrations/042_missions_complete_tooling.js');
const settings = read('featureSettings.js');
const lab = read('LabMetraPanel.js');
const settingsScreen = read('visual-packs/runtime/VisualPacksSettingsScreen.js');
const home = read('HomeScreen.js');
const missionsHome = read('MissionsHomeScreen.js');
const app = read('App.js');
const theme = read('missionTheme.js');
const db = read('missionsDb.js');
const visit = read('MissionVisitScreen.js');
const exportFile = read('missionExcelExport.js');
const importFile = read('missionExcelImport.js');
const excelSchema = read('missionExcelSchema.js');
const recipes = read('missionRecipes.js');
const missionScreen = read('MissionScreen.js');

requireText(constants, 'DATABASE_SCHEMA_VERSION = 42', 'schema v42');
requireText(migrations, "import { migration040 } from './040_missions_core.js';", 'migration 040 registered');
requireText(migrations, 'migration039, migration040', 'migration ordering 39 -> 40');
requireText(migrations, 'migration041', 'migration 041 registered');
requireText(migrations, 'migration042', 'migration 042 registered');
requireText(migration41, "name: 'missions_architecture_v2'", 'mission architecture v2');
requireText(migration41, 'CREATE TABLE IF NOT EXISTS mission_actions', 'mission actions');
requireText(migration41, 'CREATE TABLE IF NOT EXISTS mission_references', 'mission references');
requireText(migration41, 'CREATE TABLE IF NOT EXISTS mission_test_protocols', 'mission tests');
requireText(migration41, 'CREATE TABLE IF NOT EXISTS mission_scenarios', 'mission scenarios');
requireText(migration41, 'CREATE TABLE IF NOT EXISTS mission_geometries', 'mission geometries');
requireText(migration41, 'CREATE TABLE IF NOT EXISTS mission_import_rows', 'raw Excel preservation');
requireText(migration41, 'CREATE TABLE IF NOT EXISTS mission_report_sections', 'editable report sections');
requireText(migration42, "name: 'missions_complete_tooling'", 'mission complete tooling v42');
requireText(migration42, 'CREATE TABLE IF NOT EXISTS mission_installations', 'technical installations');
requireText(migration42, 'CREATE TABLE IF NOT EXISTS mission_plan_annotations', 'plan annotations');
requireText(migration42, 'CREATE TABLE IF NOT EXISTS mission_map_layers', 'SIG layers');
requireText(migration42, 'CREATE TABLE IF NOT EXISTS mission_formula_library', 'formula library');
requireText(migration42, 'CREATE TABLE IF NOT EXISTS mission_ocr_jobs', 'offline plate OCR jobs');
requireText(migration42, 'CREATE TABLE IF NOT EXISTS mission_voice_notes', 'voice notes');
requireText(migration42, 'CREATE TABLE IF NOT EXISTS mission_visit_checks', 'before-leaving checklist');
requireText(migration42, 'CREATE TABLE IF NOT EXISTS mission_document_extractions', 'document extraction');
requireText(migration42, 'CREATE TABLE IF NOT EXISTS mission_document_review_items', 'document extraction review');
requireText(migration42, 'ALTER TABLE mission_photos ADD COLUMN location_id', 'photo Room context');
requireText(migration42, 'ALTER TABLE mission_photos ADD COLUMN action_id', 'photo action context');
requireText(migration42, 'ALTER TABLE mission_photos ADD COLUMN phase_role', 'before after photo role');
requireText(migration42, 'ALTER TABLE mission_measures ADD COLUMN location_id', 'measurement Room context');
requireText(migration40, "name: 'missions_core'", 'migration identity');
requireText(migration40, 'CREATE TABLE IF NOT EXISTS missions', 'missions table');
requireText(migration40, 'CREATE TABLE IF NOT EXISTS mission_points', 'mission points');
requireText(migration40, 'CREATE TABLE IF NOT EXISTS mission_template_values', 'generic template values');
requireText(migration40, "status TEXT NOT NULL DEFAULT 'draft'", 'draft visit persistence');

for (const forbidden of ['api_remote_', 'remote_client_id', 'remote_site_id', 'api_structure_outbox']) {
  if (migration40.includes(forbidden) || migration41.includes(forbidden) || migration42.includes(forbidden)) throw new Error(`Le schéma Missions ne doit pas dépendre de l'Intranet: ${forbidden}`);
}

requireText(settings, "key: 'missions'", 'missions feature flag');
requireText(settings, 'hiddenUntilUnlocked: true', 'missions hidden before unlock');
requireText(settings, "const LAB_MISSIONS_UNLOCKED_KEY = 'lab_missions_unlocked'", 'local unlock key');
requireText(settings, "if (!row) return false", 'LAB defaults to disabled');
requireText(settings, 'getMissionsLabUnlocked()', 'unlock guard');
requireText(lab, 'delayLongPress={2000}', '2 second LAB long press');
requireText(lab, 'setMissionsVisible(false)', 'unlock does not activate Missions');
requireText(settingsScreen, "import { LabMetraPanel } from '../../LabMetraPanel.js';", 'LAB embedded in Settings');
requireText(settingsScreen, '<LabMetraPanel />', 'LAB rendered only inside Settings');
forbidText(home, 'LAB METRA', 'LAB must not be visible on home');
forbidText(home, "navigation.navigate('LabMetra')", 'home must not route to LAB');
requireText(home, 'PanResponder.create', 'home swipe responder');
requireText(home, "navigation.navigate('Missions', { enteredBySwipe: true })", 'right swipe opens Missions');
requireText(missionsHome, 'Piloter les dossiers ponctuels', 'mission-specific dashboard');
requireText(missionsHome, 'technicalVisitSwipeResponder', 'reverse swipe from Missions');
requireText(theme, "accent: '#2F7D58'", 'dedicated green Missions palette');
requireText(app, 'getMissionsVisible()', 'runtime Missions flag');
requireText(app, "current.name === 'Missions' && missionsVisible", 'guarded Missions route');
requireText(app, 'function MissionHeader', 'dedicated Missions header');
forbidText(app, "name: 'LabMetra'", 'LAB must not have a standalone route');
requireText(db, "'draft'", 'draft mission creation');
requireText(visit, 'Aucun champ de cette visite n’est obligatoire.', 'non-blocking field UX');
requireText(visit, 'Terminer quand même', 'non-blocking incomplete visit completion');
requireText(visit, '>＋ Point<', 'free point creation');
requireText(exportFile, "'00_Meta'", 'versioned Excel workbook metadata');
requireText(exportFile, 'MISSION_EXCEL_SHEETS', 'complete Excel schema export');
requireText(importFile, 'choisirEtImporterMissionExcel', 'Excel import picker');
requireText(importFile, 'raw_external', 'arbitrary workbook preservation');
requireText(importFile, 'canonical_roundtrip', 'canonical Excel round-trip');
requireText(excelSchema, "['48_Lignes_Import_Brut', 'mission_import_rows']", 'raw Excel rows exported');
requireText(excelSchema, "['65_Revue_Doc', 'mission_document_review_items']", 'v42 complete data exported');
requireText(excelSchema, 'MISSION_EXCEL_SCHEMA_VERSION = 42', 'Excel schema v42');
requireText(excelSchema, 'MISSION_TABLE_IMPORT_ORDER', 'relational import ordering');
requireText(visit, 'MISSION_CAPTURE_MODES', 'Rapide Standard Expert modes');
requireText(visit, '📷 Photo', 'mission photo quick capture');
requireText(visit, '＋ Mesure', 'mission measurement quick capture');
forbidText(recipes, 'pre_allumage', 'Missions must not reuse recurring pre-allumage recipe points');
forbidText(recipes, 'vmc-c', 'Missions must not reuse recurring VMC recipe point identifiers');
requireText(recipes, 'getMissionCapabilities', 'mission-specific feature capabilities');
requireText(missionScreen, 'getMissionCapabilities', 'Mission screen uses contextual capabilities');
requireText(recipes, "diagnostic_chaufferie_ss", 'boiler room/substation dedicated recipe');
requireText(recipes, "diagnostic_ventilation_cta", 'ventilation/CTA dedicated recipe');
requireText(recipes, "assistance_p2_p3", 'P2/P3 dedicated recipe');
requireText(recipes, "preallumage_reprise_saison", 'season restart dedicated recipe');

const typeBlock = db.match(/export const MISSION_FAMILIES = Object\.freeze\(\[([\s\S]*?)\]\);/);
if (!typeBlock) throw new Error('Impossible de lire MISSION_FAMILIES.');
const missionTypes = [...typeBlock[1].matchAll(/\['([a-z0-9_]+)'\s*,\s*'[^']+'\]/g)].map((m) => m[1]);
const recipeBlock = recipes.match(/const TYPE_RECIPES = Object\.freeze\(\{([\s\S]*?)\n\}\);/);
if (!recipeBlock) throw new Error('Impossible de lire TYPE_RECIPES.');
const missingRecipes = missionTypes.filter((type) => !new RegExp('\\n\\s{2}' + type + ':\\s*\\{').test(recipeBlock[1]));
if (missingRecipes.length) throw new Error('Types de Mission sans recette Rapide/Standard/Expert: ' + missingRecipes.join(', '));

requireText(app, "MissionEquipment", 'equipment workspace route');
requireText(app, "MissionStructure", 'patrimony hierarchy route');
requireText(read('MissionStructureScreen.js'), 'Site → Bâtiment → Niveau → Local / local technique → Équipement', 'indoor hierarchy UX');
requireText(read('missionStructureDb.js'), 'parent_location_id', 'hierarchical locations storage');
requireText(app, "MissionPlan", 'plans workspace route');
requireText(app, "MissionMeasurements", 'measurements workspace route');
requireText(app, "MissionDocumentInbox", 'document inbox route');
requireText(app, "MissionPackage", 'complete package route');
requireText(read('MissionEquipmentScreen.js'), 'Plaque signalétique · photo + OCR local', 'offline plate OCR UX');
requireText(read('missionEquipmentCatalog.js'), 'EQUIPMENT_CATEGORIES', 'structured CVC equipment catalog');
requireText(read('missionEquipmentCatalog.js'), 'MISSION_OVERLAYS', 'mission-specific equipment overlays');
requireText(read('MissionEquipmentScreen.js'), 'Caractéristiques rapides', 'quick tailored equipment capture');
requireText(read('MissionEquipmentScreen.js'), 'EQUIPMENT_PROFILE_MODES', 'Rapid Standard Expert equipment profiles');
requireText(read('MissionPlanScreen.js'), 'GeoPackage QGIS', 'QGIS GeoPackage export UX');
requireText(read('missionPlanDb.js'), 'lierAnnotationPlan', 'plan shapes linked to structured Mission objects');
requireText(read('MissionPlanScreen.js'), 'Réserve / action localisée', 'plan-localized reserves');
requireText(read('MissionPlanScreen.js'), 'Réseau technique', 'structured network drawing');
requireText(read('MissionPlanScreen.js'), 'Comptage', 'PDF counting tool');
requireText(read('MissionPlanScreen.js'), '📷 Photo', 'photo positioning from plan geometry');
requireText(read('missionPlanDb.js'), "linked_entity_type='point'", 'plan reserve geometry binding');
requireText(read('MissionPlanScreen.js'), 'Placer une signature', 'contextual PDF signature placement');
requireText(read('missionPlanDb.js'), "row.annotation_type === 'signature'", 'signature rendered into annotated PDF');
requireText(read('missionMapLayerDb.js'), 'importerRasterMission', 'offline raster import');
requireText(read('missionMapLayerDb.js'), 'importerTuilesXyzMission', 'offline XYZ tile import');
requireText(read('MissionMapScreen.js'), 'LocalTile', 'offline XYZ tile rendering');
requireText(read('MissionMapScreen.js'), 'Overlay', 'offline raster rendering');
requireText(read('MissionVisitScreen.js'), 'Avant de quitter le site', 'non-blocking before leaving checklist');
requireText(read('MissionPackageScreen.js'), 'Créer et partager le ZIP complet', 'complete mission package');
requireText(read('missionMediaDb.js'), 'resolveMissionContext', 'automatic media context inheritance');
requireText(read('MissionActionsScreen.js'), '📷 Avant', 'before photo action evidence');
requireText(read('MissionActionsScreen.js'), '📷 Après', 'after photo action evidence');
requireText(read('MissionExcelMappingScreen.js'), 'Enregistrer le mapping & appliquer', 'reusable Excel mapping');
requireText(read('MissionReportScreen.js'), 'Word', 'editable Word report export');
requireText(read('MissionReportScreen.js'), 'PDF', 'editable PDF report export');

console.log('Missions LAB contract validated: schema v42, strict Intranet isolation, offline mission tooling, complete Excel round-trip, plans/SIG, OCR, measurements, reports and packages.');
