from pathlib import Path


p = Path('wordDocxExporter.js')
s = p.read_text(encoding='utf-8')


def replace_once(old: str, new: str, label: str):
    global s
    if new in s:
        return
    if old not in s:
        raise SystemExit(f'{label} marker not found')
    s = s.replace(old, new, 1)


# Use a DOCX package generated by python-docx as the runtime skeleton. This keeps
# Word's standard settings, font table, theme, styles, package metadata and
# relationship conventions instead of constructing an ultra-minimal ZIP by hand.
import_marker = "import { REPORT_COVER, REPORT_LOGO, REPORT_OPQIBI } from './reportBrandAssets.js';\n"
import_line = "import { WORD_DOCX_TEMPLATE_BASE64 } from './wordDocxTemplate.generated.js';\n"
if import_line not in s:
    if import_marker not in s:
        raise SystemExit('Word template import marker not found')
    s = s.replace(import_marker, import_marker + import_line, 1)

old_setup = """  const root = `${FileSystem.cacheDirectory}metra-docx-${stamp}/`;
  const word = `${root}word/`, rels = `${root}_rels/`, wordRels = `${word}_rels/`, media = `${word}media/`, props = `${root}docProps/`;
  await FileSystem.makeDirectoryAsync(wordRels, { intermediates: true });
  await FileSystem.makeDirectoryAsync(media, { intermediates: true });
  await FileSystem.makeDirectoryAsync(rels, { intermediates: true });
  await FileSystem.makeDirectoryAsync(props, { intermediates: true });

  const relationships = [{ id: 'rIdStyles', type: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles', target: 'styles.xml' }];
  const images = [];
  let nextRel = 2;
"""
new_setup = r'''  const root = `${FileSystem.cacheDirectory}metra-docx-${stamp}/`;
  const templateUri = `${FileSystem.cacheDirectory}metra-office-template-${stamp}.docx`;
  await FileSystem.deleteAsync(root, { idempotent: true }).catch(() => {});
  await FileSystem.deleteAsync(templateUri, { idempotent: true }).catch(() => {});
  await writeBase64Async(templateUri, WORD_DOCX_TEMPLATE_BASE64, 'gabarit DOCX Office');
  await FileSystem.makeDirectoryAsync(root, { intermediates: true });
  try {
    await unzip(nativePath(templateUri), nativePath(root), 'UTF-8');
  } finally {
    await FileSystem.deleteAsync(templateUri, { idempotent: true }).catch(() => {});
  }

  const word = `${root}word/`, rels = `${root}_rels/`, wordRels = `${word}_rels/`, media = `${word}media/`, props = `${root}docProps/`;
  await FileSystem.makeDirectoryAsync(media, { intermediates: true });

  // python-docx's blank package declares JPEG but not PNG. METRA's exact
  // branding assets are PNG, so register PNG without replacing the standard
  // content-types document.
  const contentTypesUri = `${root}[Content_Types].xml`;
  let packageContentTypes = await FileSystem.readAsStringAsync(contentTypesUri);
  if (!/Extension=["']png["']/i.test(packageContentTypes)) {
    packageContentTypes = packageContentTypes.replace(
      '</Types>',
      '<Default Extension="png" ContentType="image/png"/></Types>',
    );
    await FileSystem.writeAsStringAsync(contentTypesUri, packageContentTypes);
  }

  // Keep all standard document relationships from the Office skeleton and add
  // METRA media with IDs that cannot collide with the template rId1..rId8.
  const relationships = [];
  const images = [];
  let nextRel = 100;
'''
replace_once(old_setup, new_setup, 'Office skeleton package setup')

old_image_paragraph = """function imageParagraph(relId, widthEmu, heightEmu, docPrId, name, align = 'center') {
  return `<w:p><w:pPr><w:jc w:val=\"${align}\"/><w:spacing w:after=\"120\"/></w:pPr><w:r><w:drawing><wp:inline distT=\"0\" distB=\"0\" distL=\"0\" distR=\"0\"><wp:extent cx=\"${widthEmu}\" cy=\"${heightEmu}\"/><wp:effectExtent l=\"0\" t=\"0\" r=\"0\" b=\"0\"/><wp:docPr id=\"${docPrId}\" name=\"${esc(name)}\"/><wp:cNvGraphicFramePr/><a:graphic><a:graphicData uri=\"http://schemas.openxmlformats.org/drawingml/2006/picture\"><pic:pic><pic:nvPicPr><pic:cNvPr id=\"${docPrId}\" name=\"${esc(name)}\"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:embed=\"${relId}\"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x=\"0\" y=\"0\"/><a:ext cx=\"${widthEmu}\" cy=\"${heightEmu}\"/></a:xfrm><a:prstGeom prst=\"rect\"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r></w:p>`;
}
"""
new_image_paragraph = r'''function imageParagraph(relId, widthEmu, heightEmu, docPrId, name, align = 'center') {
  return `<w:p><w:pPr><w:jc w:val="${align}"/><w:spacing w:after="120"/></w:pPr><w:r><w:drawing><wp:inline distT="0" distB="0" distL="0" distR="0"><wp:extent cx="${widthEmu}" cy="${heightEmu}"/><wp:effectExtent l="0" t="0" r="0" b="0"/><wp:docPr id="${docPrId}" name="${esc(name)}"/><wp:cNvGraphicFramePr><a:graphicFrameLocks noChangeAspect="1"/></wp:cNvGraphicFramePr><a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:pic><pic:nvPicPr><pic:cNvPr id="${docPrId}" name="${esc(name)}"/><pic:cNvPicPr><a:picLocks noChangeAspect="1"/></pic:cNvPicPr></pic:nvPicPr><pic:blipFill><a:blip r:embed="${relId}"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="${widthEmu}" cy="${heightEmu}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r></w:p>`;
}
'''
replace_once(old_image_paragraph, new_image_paragraph, 'canonical DrawingML image')

old_document_xml = """  const documentXml = `<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><w:document xmlns:w=\"http://schemas.openxmlformats.org/wordprocessingml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\" xmlns:wp=\"http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing\" xmlns:a=\"http://schemas.openxmlformats.org/drawingml/2006/main\" xmlns:pic=\"http://schemas.openxmlformats.org/drawingml/2006/picture\"><w:body>${body.join('')}</w:body></w:document>`;
  const documentRels = `<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">${relationships.map((rel) => `<Relationship Id=\"${rel.id}\" Type=\"${rel.type}\" Target=\"${rel.target}\"/>`).join('')}</Relationships>`;
"""
new_document_xml = r'''  const documentXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas" xmlns:mo="http://schemas.microsoft.com/office/mac/office/2008/main" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:mv="urn:schemas-microsoft-com:mac:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns:wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup" xmlns:wpi="http://schemas.microsoft.com/office/word/2010/wordprocessingInk" xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml" xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture" mc:Ignorable="w14 wp14"><w:body>${body.join('')}</w:body></w:document>`;
  const baseDocumentRels = await FileSystem.readAsStringAsync(`${wordRels}document.xml.rels`);
  const imageRelationshipsXml = relationships.map((rel) => `<Relationship Id="${rel.id}" Type="${rel.type}" Target="${rel.target}"/>`).join('');
  if (!baseDocumentRels.includes('</Relationships>')) throw new Error('Gabarit Word invalide : relations document absentes.');
  const documentRels = baseDocumentRels.replace('</Relationships>', `${imageRelationshipsXml}</Relationships>`);
'''
replace_once(old_document_xml, new_document_xml, 'standard document namespaces and relationships')

old_writes = """  await Promise.all([
    FileSystem.writeAsStringAsync(`${root}[Content_Types].xml`, contentTypes()),
    FileSystem.writeAsStringAsync(`${rels}.rels`, packageRels),
    FileSystem.writeAsStringAsync(`${word}document.xml`, documentXml),
    FileSystem.writeAsStringAsync(`${word}styles.xml`, stylesXml()),
    FileSystem.writeAsStringAsync(`${wordRels}document.xml.rels`, documentRels),
    FileSystem.writeAsStringAsync(`${props}core.xml`, core),
    FileSystem.writeAsStringAsync(`${props}app.xml`, app),
  ]);
"""
new_writes = r'''  // Only replace the dynamic document and its media relationships. All other
  // package parts remain those of the standards-compliant DOCX skeleton.
  await Promise.all([
    FileSystem.writeAsStringAsync(`${word}document.xml`, documentXml),
    FileSystem.writeAsStringAsync(`${wordRels}document.xml.rels`, documentRels),
  ]);
'''
replace_once(old_writes, new_writes, 'preserve Office template package parts')

# Validate more than the previous minimal package check: Word for Android is
# stricter about standard settings/theme/font parts than a simple ZIP parser.
old_required = """      'word/styles.xml',
      'word/_rels/document.xml.rels',
      'docProps/core.xml',
      'docProps/app.xml',
"""
new_required = """      'word/styles.xml',
      'word/settings.xml',
      'word/fontTable.xml',
      'word/theme/theme1.xml',
      'word/_rels/document.xml.rels',
      'docProps/core.xml',
      'docProps/app.xml',
"""
replace_once(old_required, new_required, 'Office package validation parts')

p.write_text(s, encoding='utf-8')
print('Word exporter now rebuilds reports from a standards-compliant Office DOCX skeleton.')
