const { spawnSync } = require('child_process');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');

const CONTRACT_CHECKS = [
  ['N.S comment persistence contract', '.github/scripts/check_ns_comment_persistence.js'],
  ['latest API visit runtime contract', '.github/scripts/check_api_latest_visit_runtime.js'],
  ['Intranet equipment import + brand logo contract', '.github/scripts/check_intranet_equipment_import.js'],
  ['Intranet equipment import executable regression', '.github/scripts/test_intranet_equipment_import.js'],
  ['visit carry-forward contract', '.github/scripts/check_visit_carry_forward_contract.js'],
  ['large-client performance contract', '.github/scripts/check_large_client_performance.js'],
  ['runtime responsiveness v3 contract', '.github/scripts/check_runtime_responsiveness_v3.js'],
  ['startup dependency graph contract', '.github/scripts/check_startup_dependency_graph.js'],
  ['database initialization concurrency', '.github/scripts/test_db_initialization.js'],
  ['report export workflow contract', '.github/scripts/check_report_export_workflow.js'],
  ['latest visit photos contract', '.github/scripts/check_latest_visit_photos_contract.js'],
  ['visit photo cleanup', '.github/scripts/test_visit_photo_cleanup.js'],
  ['Intranet visit upload contract', '.github/scripts/check_intranet_visit_upload_contract.js'],
  ['Intranet structure creation contract', '.github/scripts/check_intranet_structure_creation_contract.js'],
  ['Intranet any-visit binding contract', '.github/scripts/check_intranet_any_visit_contract.js'],
  ['Intranet LOCAL name sync contract', '.github/scripts/check_intranet_local_name_sync.js'],
  ['SITE/LOCAL navigation contract', '.github/scripts/check_site_local_navigation_contract.js'],
  ['SITE/LOCAL identity executable tests', '.github/scripts/test_site_local_identity_repair.js'],
  ['Intranet LOCAL name sync executable tests', '.github/scripts/test_intranet_local_name_sync.js'],
  ['Intranet mapping/support dump executable tests', '.github/scripts/test_intranet_mapping_support_dump.js'],
  ['Intranet visit upload executable tests', '.github/scripts/test_intranet_visit_upload.js'],
  ['Intranet any-visit binding executable tests', '.github/scripts/test_intranet_any_visit_binding.js'],
  ['Intranet first-visit preparation executable tests', '.github/scripts/test_intranet_first_visit_preparation.js'],
  ['Intranet focused upload audit', '.github/scripts/test_intranet_visit_upload_audit.js'],
  ['photo workflow executable regression tests', '.github/scripts/test_photo_workflow.js'],
  ['Missions LAB isolation contract', '.github/scripts/check_missions_lab_contract.js'],
  ['Missions app compatibility contract', '.github/scripts/check_missions_app_compat.js'],
  ['phone companion contract', '.github/scripts/check_companion_mode_contract.js'],
  ['phone photo mode contract', '.github/scripts/check_phone_photo_mode_contract.js'],
  ['navigation + site sort contract', '.github/scripts/check_navigation_sort_contract.js'],
  ['durable visit data contract', '.github/scripts/check_durable_visit_data_contract.js'],
  ['field runtime foundation', '.github/scripts/check_field_runtime_foundation.js'],
  ['instant camera runtime', '.github/scripts/check_camera_runtime_contract.js'],
];

const JS_SYNTAX_FILES = [
  'PersistentControleGenerique.js',
  'VmcControleGenerique.js',
  'PresetControleGenerique.js',
  'DurableChampGenerique.js',
  'durableAutosave.js',
  'PhotoButton.js',
  'photoPersistenceJournal.js',
  'boundedCache.js',
  'visitRuntimeCache.js',
  'visitPrewarm.js',
  'visitPreviousSnapshot.js',
  'navigationPrewarm.js',
  'useListScrollMemory.js',
  'saveActivity.js',
  'photoVariantCache.js',
  'PhotoVariantImage.js',
  'photoRuntimeCache.js',
  'photoCaptureContext.js',
  'cameraRuntime.js',
  'App.js',
  'ReportScreen.js',
  'reportBuilder.js',
  'reportEditorExporter.js',
  'metraStorage.js',
  'ClientDocumentsScreen.js',
  'HomeScreen.js',
  'ClientSitesScreen.js',
  'siteSort.js',
  'navigationMemory.js',
  'SiteGroupsManager.js',
  'SiteVisitesScreen.js',
  'SiteLocalsScreen.js',
  'intranetIdentityRepairDb.js',
  'SiteOverviewPanel.js',
  'VisiteScreen.js',
  'ParametresScreen.js',
  'supportDump.js',
  'visitPrefillDb.js',
  'visitCarryForwardDb.js',
  'visitCreationDb.js',
  'ClientMapScreen.js',
  'EquipmentCatalogueBrowser.js',
  'ClientPilotageScreen.js',
  'ClientPatrimoineScreen.js',
  'clientTechnicalMatrix.js',
  'patrimoineDb.js',
  'persistentEquipmentDb.js',
  'siteHealth.js',
  'db.js',
  'database/index.js',
  'featureSettings.js',
  'LabMetraPanel.js',
  'missionsDb.js',
  'missionVisitDb.js',
  'missionRecipes.js',
  'missionFieldPlaybooks.js',
  'missionVisitAutofillDb.js',
  'missionVisitMemoryDb.js',
  'missionReportRecipes.js',
  'missionTestPresets.js',
  'missionDocumentPresets.js',
  'missionExcelExport.js',
  'missionClientExcelExport.js',
  'missionExcelImport.js',
  'missionExcelAutoMap.js',
  'missionExcelSchema.js',
  'missionDomainDb.js',
  'missionMediaDb.js',
  'missionNativeTools.js',
  'missionEquipmentDb.js',
  'missionEquipmentCatalog.js',
  'missionStructureDb.js',
  'missionTechnicalStructureDb.js',
  'missionVisitQualityDb.js',
  'missionPlanDb.js',
  'missionMapLayerDb.js',
  'missionCalculationDb.js',
  'missionCalculationAssist.js',
  'missionScenarioPresets.js',
  'missionTestDb.js',
  'missionExcelMappingDb.js',
  'missionPhotoAnnotationDb.js',
  'missionPhotoAlbumExport.js',
  'missionMeasurementDb.js',
  'missionMeasurementCampaignDb.js',
  'missionDocumentExtractionDb.js',
  'missionPackageExport.js',
  'missionPackageImport.js',
  'missionReportDb.js',
  'missionReportExporter.js',
  'missionTheme.js',
  'MissionsHomeScreen.js',
  'MissionCreateScreen.js',
  'MissionScreen.js',
  'MissionVisitScreen.js',
  'MissionReportScreen.js',
  'MissionTechnicalGraphScreen.js',
  'MissionEquipmentScreen.js',
  'MissionStructureScreen.js',
  'MissionTechnicalStructureScreen.js',
  'MissionPlanScreen.js',
  'MissionMapScreen.js',
  'MissionCalculationScreen.js',
  'MissionTestsScreen.js',
  'MissionScenarioScreen.js',
  'MissionExcelMappingScreen.js',
  'MissionPhotoAnnotationScreen.js',
  'MissionActionsScreen.js',
  'MissionDocumentsScreen.js',
  'MissionSignatureScreen.js',
  'MissionWorkflowScreen.js',
  'MissionPackageScreen.js',
  'MissionDocumentInboxScreen.js',
  'MissionMeasurementsScreen.js',
  'MissionMeasurementCampaignScreen.js',
  'MissionReserveClearanceScreen.js',
  'MissionSubjectsScreen.js',
  'MissionP3DashboardScreen.js',
  'MissionExpertiseScreen.js',
  'MissionCampaignDashboardScreen.js',
  'MissionAmoDashboardScreen.js',
  'MissionControlBoardScreen.js',
  'missionWorkstreamPresets.js',
  'MissionReceptionBoardScreen.js',
  'visual-packs/runtime/VisualPacksSettingsScreen.js',
  'visual-packs/runtime/visualPackManager.js',
  'symfonyApiCacheDb.js',
  'apiLatestVisitImportDb.js',
  'apiLatestVisitFieldEnrichmentDb.js',
  'MetraDirectoryScreen.js',
  'ClientLatestVisitPhotosModal.js',
  'latestVisitPhotoModel.js',
  'latestVisitPhotoTasks.js',
  'PhotoDownloadStatus.js',
  'PhotoReferenceAccess.js',
  'ReferencePhotoViewer.js',
  'SitePhotoPreparationOption.js',
  'latestVisitPhotosDb.js',
  'latestVisitPhotosStorage.js',
  'intranetVisitPayload.js',
  'intranetVisitBindingDb.js',
  'intranetVisitOutboxDb.js',
  'intranetVisitPhotoOutboxDb.js',
  'intranetStructureDb.js',
  'IntranetStructureUi.js',
  'IntranetStructureRuntime.js',
  'IntranetStructureScreen.js',
  'IntranetVisitSync.js',
  'IntranetVisitDestinationPicker.js',
  'database/migrations/033_intranet_visit_outbox.js',
  'database/migrations/034_intranet_local_name_sync.js',
  'database/migrations/035_client_site_images.js',
  'database/migrations/036_intranet_visit_photo_outbox.js',
  'database/migrations/037_intranet_server_schema_alignment.js',
  'database/migrations/038_intranet_structure_creation.js',
  'database/migrations/039_intranet_structure_outbox_alignment.js',
  'database/migrations/040_missions_core.js',
  'database/migrations/041_missions_architecture.js',
  'database/migrations/042_missions_complete_tooling.js',
  'database/migrations/043_missions_measurement_campaigns.js',
  'plugins/withMetraMissionTools.js',
  'plugins/withMetraCompanion.js',
  'companionNative.js',
  'companionProtocol.js',
  'companionOutbox.js',
  'companionData.js',
  'MetraCvcIcons.js',
  'CompanionTabletModal.js',
  'CompanionPhoneScreen.js',
  'PhotoPhoneScreen.js',
  'photoModeData.js',
  'app.config.js',
  'symfonyApi.js',
  'database/migrations/031_latest_visit_photos.js',
  'database/migrations/032_photo_reference_workflow.js',
];

function runNode(args, label) {
  const startedAt = Date.now();
  console.log(`\n[METRA verify] ${label}`);
  const result = spawnSync(process.execPath, args, {
    cwd: ROOT,
    stdio: 'inherit',
    env: process.env,
  });
  if (result.error) {
    console.error(`[METRA verify] ${label} could not start: ${result.error.message}`);
    process.exit(1);
  }
  if (result.status !== 0) {
    console.error(`[METRA verify] ${label} failed with exit code ${result.status}.`);
    console.error('[METRA verify] Runtime source is not in the committed prepared state. Do not repair it during install; update the source and its contracts in a dedicated PR.');
    process.exit(result.status || 1);
  }
  console.log(`[METRA verify] ${label} OK (${Date.now() - startedAt} ms)`);
}

console.log('[METRA verify] Verifying committed runtime source without modifying it.');
for (const [label, script] of CONTRACT_CHECKS) runNode([script], `contract: ${label}`);

console.log('\n[METRA verify] Validating JavaScript syntax.');
for (const file of JS_SYNTAX_FILES) runNode(['--check', file], `syntax: ${file}`);

console.log('\n[METRA verify] Committed runtime source is valid. No source patch was applied.');
