const fs = require('fs');
const path = require('path');

module.exports = ({ config }) => {
  const key = String(process.env.GOOGLE_MAPS_API_KEY || '').trim();
  const android = config.android || {};
  const androidConfig = android.config || {};

  // Keep JavaScript and the generated Android manifest on the exact same
  // source of truth. The file is also committed with `false` as a safe
  // default, then regenerated by Expo whenever the app config is evaluated.
  const runtimeFile = path.join(__dirname, 'googleMapsRuntime.generated.js');
  fs.writeFileSync(
    runtimeFile,
    `// Generated by app.config.js - do not edit manually.\nexport const GOOGLE_MAPS_BUILD_ENABLED = ${key ? 'true' : 'false'};\n`,
    'utf8'
  );

  return {
    ...config,
    android: {
      ...android,
      config: key
        ? { ...androidConfig, googleMaps: { ...(androidConfig.googleMaps || {}), apiKey: key } }
        : androidConfig,
    },
    extra: {
      ...(config.extra || {}),
      googleMapsConfigured: Boolean(key),
    },
  };
};
