import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Image, Modal, ScrollView, Text, TouchableOpacity, View } from 'react-native';
import { COLORS, styles } from './styles.js';
import { getClientTechnicalMatrix, getMatrixCellPhotos } from './clientTechnicalMatrix.js';
import { reserveSeverityLabel } from './reserveSeverity.js';

const STATE = {
  green: { bg: '#E8F5E9', border: '#2E7D32', text: '#1B5E20', symbol: '✓' },
  orange: { bg: '#FFF3E0', border: '#EF8B2C', text: '#9A4E00', symbol: '!' },
  red: { bg: '#FDECEC', border: '#B42318', text: '#B42318', symbol: '!' },
  unknown: { bg: '#F2F4F7', border: '#667085', text: '#475467', symbol: '?' },
  neutral: { bg: '#F7F7F7', border: '#98A2B3', text: '#667085', symbol: '·' },
  none: { bg: '#FAFAFA', border: '#D0D5DD', text: '#98A2B3', symbol: '—' },
};

function Cell({ cell, onPress }) { const p = STATE[cell.state] || STATE.none; const count = cell.ns || cell.nr || cell.nv || cell.s || 0; return <TouchableOpacity disabled={!cell.total} onPress={onPress} style={{ width: 92, minHeight: 58, margin: 3, borderRadius: 10, borderWidth: 1.5, borderColor: p.border, backgroundColor: p.bg, alignItems: 'center', justifyContent: 'center' }}><Text style={{ fontSize: 18, fontWeight: '900', color: p.text }}>{p.symbol} {count || ''}</Text><Text style={{ fontSize: 8.5, color: p.text, marginTop: 2 }}>{cell.total ? `${cell.s} S · ${cell.ns} N.S` : 'Non concerné'}</Text></TouchableOpacity>; }

export function ClientTechnicalMatrixScreen({ route, navigation }) {
  const { clientId, nomClient } = route.params || {}; const [data, setData] = useState(null); const [selected, setSelected] = useState(null); const [photos, setPhotos] = useState({}); const [photoZoom, setPhotoZoom] = useState(null);
  const load = useCallback(async () => setData(await getClientTechnicalMatrix(clientId)), [clientId]); useEffect(() => { load(); }, [load]);
  const openCell = async (site, category, cell) => { setSelected({ site, category, cell }); const map = {}; for (const issue of cell.issues || []) map[`${issue.id}-${issue.cle}`] = await getMatrixCellPhotos(issue); setPhotos(map); };
  if (!data) return <View style={styles.center}><ActivityIndicator size="large" color={COLORS.orange}/></View>;
  return <View style={{ flex: 1, backgroundColor: COLORS.bg }}><View style={{ padding: 12, borderBottomWidth: 1, borderBottomColor: COLORS.line }}><Text style={{ fontWeight: '900', fontSize: 17, color: COLORS.ink }}>Cartographie technique · {nomClient || 'Client'}</Text><Text style={{ color: COLORS.muted, fontSize: 11, marginTop: 3 }}>Vert = OK · orange = à traiter · rouge = critique · gris = information incomplète. Les métiers restent séparés dans les données.</Text></View><ScrollView horizontal contentContainerStyle={{ padding: 8 }}><View><View style={{ flexDirection: 'row' }}><View style={{ width: 180, padding: 8 }}><Text style={{ fontWeight: '900' }}>Sites</Text></View>{data.categories.map((c) => <View key={c.key} style={{ width: 98, padding: 6, justifyContent: 'center' }}><Text style={{ textAlign: 'center', fontSize: 10, fontWeight: '800' }}>{c.label}</Text></View>)}</View><ScrollView>{data.sites.map((site) => <View key={site.id} style={{ flexDirection: 'row', borderTopWidth: 1, borderTopColor: COLORS.line, alignItems: 'center' }}><TouchableOpacity onPress={() => navigation.navigate('SiteVisites', { siteId: site.id, nomSite: site.nom_site })} style={{ width: 180, padding: 9 }}><Text style={{ fontWeight: '800', color: COLORS.primary }}>{site.nom_site}</Text><Text style={{ fontSize: 9.5, color: COLORS.muted }} numberOfLines={2}>{site.adresse || 'Adresse non renseignée'}</Text></TouchableOpacity>{data.categories.map((c) => <Cell key={c.key} cell={site.cells[c.key]} onPress={() => openCell(site, c, site.cells[c.key])}/>)}</View>)}</ScrollView></View></ScrollView>
    <Modal visible={!!selected} transparent animationType="fade" onRequestClose={() => setSelected(null)}><View style={styles.modalOverlay}><View style={[styles.modalSheet, { maxWidth: 720, width: '94%', maxHeight: '88%' }]}>{selected ? <ScrollView><Text style={styles.modalTitle}>{selected.site.nom_site} · {selected.category.label}</Text><Text style={{ color: COLORS.muted, marginTop: 3 }}>{selected.cell.s} satisfaisant(s) · {selected.cell.ns} N.S · {selected.cell.nr} N.R · {selected.cell.nv} N.V</Text>{selected.cell.issues.map((issue, idx) => { const pics = photos[`${issue.id}-${issue.cle}`] || []; return <View key={`${issue.id}-${issue.cle}-${idx}`} style={{ marginTop: 12, borderWidth: 1, borderColor: COLORS.line, borderRadius: 12, padding: 11 }}><Text style={{ fontWeight: '900', color: COLORS.red }}>{issue.reference_libelle || issue.cle} · {reserveSeverityLabel(issue.criticite)}</Text><Text style={{ marginTop: 5, color: COLORS.ink }}>{issue.prestation || issue.commentaire || 'Anomalie à préciser'}</Text>{pics.length ? <ScrollView horizontal style={{ marginTop: 8 }}>{pics.map((p) => <TouchableOpacity key={p.id} onPress={() => setPhotoZoom({ ...p, issue })}><Image source={{ uri: p.uri }} style={{ width: 105, height: 78, borderRadius: 8, marginRight: 7, backgroundColor: '#eee' }}/></TouchableOpacity>)}</ScrollView> : <Text style={{ marginTop: 7, fontSize: 10, color: COLORS.muted }}>Aucune photo liée à ce problème.</Text>}</View>; })}<View style={{ flexDirection: 'row', gap: 8, marginTop: 14 }}><TouchableOpacity style={[styles.btnPrimary, { flex: 1 }]} onPress={() => { const s = selected.site; setSelected(null); navigation.navigate('SiteVisites', { siteId: s.id, nomSite: s.nom_site }); }}><Text style={styles.btnPrimaryText}>Ouvrir le site</Text></TouchableOpacity><TouchableOpacity style={[styles.btnSecondary, { flex: 1 }]} onPress={() => setSelected(null)}><Text style={styles.btnSecondaryText}>Fermer</Text></TouchableOpacity></View></ScrollView> : null}</View></View></Modal>
    <Modal visible={!!photoZoom} transparent animationType="fade" onRequestClose={() => setPhotoZoom(null)}><View style={styles.modalOverlay}><View style={[styles.modalSheet, { width: '96%', maxWidth: 900 }]}>{photoZoom ? <><Image source={{ uri: photoZoom.uri }} resizeMode="contain" style={{ width: '100%', height: 430, backgroundColor: '#111', borderRadius: 10 }}/><Text style={{ marginTop: 9, fontWeight: '800' }}>{photoZoom.label || photoZoom.issue?.reference_libelle || photoZoom.issue?.cle}</Text><TouchableOpacity style={[styles.btnPrimary, { marginTop: 12 }]} onPress={() => setPhotoZoom(null)}><Text style={styles.btnPrimaryText}>Revenir à la synthèse</Text></TouchableOpacity></> : null}</View></View></Modal>
  </View>;
}
