export const MISSION_EXCEL_FORMAT = 'METRA_MISSIONS_XLSX_V2';
export const MISSION_EXCEL_SCHEMA_VERSION = 41;

// Canonical workbook contract. Only Missions tables are included: never Intranet / recurring visit tables.
export const MISSION_EXCEL_SHEETS = Object.freeze([
  ['01_Mission', 'missions'],
  ['02_Clients', 'mission_clients'],
  ['03_Sites', 'mission_sites'],
  ['04_Mission_Sites', 'mission_site_links'],
  ['05_Localisations', 'mission_locations'],
  ['06_Phases', 'mission_phases'],
  ['07_Visites', 'mission_visits'],
  ['08_Points', 'mission_points'],
  ['09_Historique_Points', 'mission_point_history'],
  ['10_Point_Acteurs', 'mission_point_actors'],
  ['11_Acteurs', 'mission_actors'],
  ['12_Equipements', 'mission_equipment'],
  ['13_Mesures', 'mission_measures'],
  ['14_Photos', 'mission_photos'],
  ['15_Documents', 'mission_documents'],
  ['16_Notes', 'mission_notes'],
  ['17_Valeurs_Trames', 'mission_template_values'],
  ['18_Volets', 'mission_workstreams'],
  ['19_Sujets', 'mission_subjects'],
  ['20_Constats', 'mission_observations'],
  ['21_Hypotheses', 'mission_hypotheses'],
  ['22_Decisions', 'mission_decisions'],
  ['23_Actions', 'mission_actions'],
  ['24_References', 'mission_references'],
  ['25_Series_Mesures', 'mission_measure_series'],
  ['26_Protocoles_Essais', 'mission_test_protocols'],
  ['27_Etapes_Essais', 'mission_test_steps'],
  ['28_Executions_Essais', 'mission_test_runs'],
  ['29_Resultats_Essais', 'mission_test_results'],
  ['30_Documents_Attendus', 'mission_expected_documents'],
  ['31_Validations', 'mission_validations'],
  ['32_Scenarios', 'mission_scenarios'],
  ['33_Scenario_Actions', 'mission_scenario_actions'],
  ['34_Geometries', 'mission_geometries'],
  ['35_Relations_Equipements', 'mission_equipment_relations'],
  ['36_Calculs', 'mission_calculations'],
  ['37_Annotations_Photos', 'mission_photo_annotations'],
  ['38_Signatures', 'mission_signatures'],
  ['39_Cycle_Vie_Equip', 'mission_equipment_lifecycle'],
  ['40_Provenance', 'mission_provenance'],
  ['41_Profils_Rapport', 'mission_report_profiles'],
  ['42_Sections_Rapport', 'mission_report_sections'],
  ['43_Sorties_Rapport', 'mission_report_outputs'],
  ['44_Details_Points', 'mission_point_details'],
  ['45_Details_Mesures', 'mission_measure_details'],
  ['46_Imports', 'mission_import_batches'],
  ['47_Problemes_Import', 'mission_import_issues'],
  ['48_Lignes_Import_Brut', 'mission_import_rows'],
]);

export const MISSION_TABLE_BY_SHEET = Object.freeze(
  Object.fromEntries(MISSION_EXCEL_SHEETS.map(([sheet, table]) => [sheet, table]))
);

export const MISSION_CANONICAL_TABLES = Object.freeze(MISSION_EXCEL_SHEETS.map(([, table]) => table));

export const MISSION_TABLE_IMPORT_ORDER = Object.freeze([
  'mission_clients',
  'mission_sites',
  'missions',
  'mission_site_links',
  'mission_locations',
  'mission_phases',
  'mission_visits',
  'mission_actors',
  'mission_equipment',
  'mission_points',
  'mission_point_history',
  'mission_point_actors',
  'mission_measures',
  'mission_notes',
  'mission_documents',
  'mission_photos',
  'mission_template_values',
  'mission_workstreams',
  'mission_subjects',
  'mission_observations',
  'mission_hypotheses',
  'mission_decisions',
  'mission_references',
  'mission_measure_series',
  'mission_actions',
  'mission_test_protocols',
  'mission_test_steps',
  'mission_test_runs',
  'mission_test_results',
  'mission_expected_documents',
  'mission_validations',
  'mission_scenarios',
  'mission_scenario_actions',
  'mission_geometries',
  'mission_equipment_relations',
  'mission_calculations',
  'mission_photo_annotations',
  'mission_signatures',
  'mission_equipment_lifecycle',
  'mission_provenance',
  'mission_report_profiles',
  'mission_report_sections',
  'mission_report_outputs',
  'mission_point_details',
  'mission_measure_details',
]);

export function sheetForTable(tableName) {
  return MISSION_EXCEL_SHEETS.find(([, table]) => table === tableName)?.[0] || null;
}
