import { createId } from './ids.js';
const VERIFIED_AT='2026-08-23';
async function ensureCategory(db,nom,icone='⚙️',ordre=95){let r=await db.getFirstAsync('SELECT id FROM categories_equipement WHERE nom=? COLLATE NOCASE',[nom]);const id=r?.id||createId('cat');if(!r)await db.runAsync('INSERT INTO categories_equipement(id,nom,icone,ordre) VALUES(?,?,?,?)',[id,nom,icone,ordre]);else await db.runAsync('UPDATE categories_equipement SET actif=1,icone=? WHERE id=?',[icone,id]);return id;}
async function ensureBrand(db,nom){let r=await db.getFirstAsync('SELECT id FROM marques_equipement WHERE nom=? COLLATE NOCASE',[nom]);const id=r?.id||createId('brand');if(!r)await db.runAsync('INSERT INTO marques_equipement(id,nom) VALUES(?,?)',[id,nom]);else await db.runAsync('UPDATE marques_equipement SET actif=1 WHERE id=?',[id]);return id;}
async function ensureModel(db,{category,brand,name,desc,source,image,aliases,lifecycle='actuel'}){const cid=await ensureCategory(db,category,category==='Variateur de fréquence'?'⚡':category==='Rooftop'?'🏢':category==='DRV / VRV'?'❄️':'⚙️');const bid=await ensureBrand(db,brand);let r=await db.getFirstAsync('SELECT id FROM modeles_equipement WHERE categorie_id=? AND marque_id=? AND nom=? COLLATE NOCASE',[cid,bid,name]);const id=r?.id||createId('model');if(!r)await db.runAsync(`INSERT INTO modeles_equipement(id,categorie_id,marque_id,nom,caracteristiques,mots_cles,source_uri,data_quality,verified_at,image_uri,lifecycle_status,aliases) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`,[id,cid,bid,name,desc,`${category} ${brand} ${name} ${aliases||''}`,source,'verified_range',VERIFIED_AT,image||null,lifecycle,aliases||null]);else await db.runAsync(`UPDATE modeles_equipement SET actif=1,caracteristiques=?,source_uri=?,data_quality='verified_range',verified_at=?,image_uri=COALESCE(?,image_uri),lifecycle_status=?,aliases=COALESCE(?,aliases) WHERE id=?`,[desc,source,VERIFIED_AT,image||null,lifecycle,aliases||null,id]);return id;}
async function ensureVariant(db,{modelId,name,source,specs=[]}){let r=await db.getFirstAsync('SELECT id FROM variantes_equipement WHERE modele_id=? AND nom=? COLLATE NOCASE',[modelId,name]);const id=r?.id||createId('variant');if(!r)await db.runAsync(`INSERT INTO variantes_equipement(id,modele_id,nom,source_uri,data_quality,verified_at) VALUES(?,?,?,?,?,?)`,[id,modelId,name,source,'verified_range',VERIFIED_AT]);await db.runAsync('DELETE FROM caracteristiques_equipement WHERE variante_id=?',[id]);let o=0;for(const [k,v,u] of specs)await db.runAsync(`INSERT INTO caracteristiques_equipement(id,variante_id,cle,valeur,unite,ordre) VALUES(?,?,?,?,?,?)`,[createId('spec'),id,k,String(v),u||null,o++]);if(source){const d=await db.getFirstAsync('SELECT id FROM documents_equipement WHERE variante_id=? AND uri=?',[id,source]);if(!d)await db.runAsync(`INSERT INTO documents_equipement(id,variante_id,type,nom,uri,langue) VALUES(?,?,?,?,?,?)`,[createId('doc'),id,'Page constructeur','Page produit constructeur',source,'FR']);}return id;}

export async function seedEquipmentCatalogPeripheral(db){const done=await db.getFirstAsync(`SELECT value FROM _meta WHERE key='equipment_catalog_peripheral_v1'`);if(done)return;
  const fc102=await ensureModel(db,{category:'Variateur de fréquence',brand:'Danfoss',name:'VLT HVAC Drive FC 102',desc:'Variateur dédié HVAC pour pompes, ventilateurs et compresseurs, fonctions bâtiment et surveillance conditionnelle.',source:'https://www.danfoss.com/fr-fr/products/dds/low-voltage-drives/vlt-drives/vlt-hvac-drive-fc-102/',aliases:'VFD drive variateur HVAC FC102'});
  await ensureVariant(db,{modelId:fc102,name:'FC 102 - gamme',source:'https://www.danfoss.com/fr-fr/products/dds/low-voltage-drives/vlt-drives/vlt-hvac-drive-fc-102/',specs:[['Puissance 1x200-240 V','1.1–22','kW'],['Puissance 3x200-240 V','1.1–160','kW'],['Puissance 3x380-480 V','1.1–560','kW'],['Puissance 3x525-690 V','1.1–800','kW'],['Protection IEC','IP00 / IP20 / IP21 / IP54 / IP55 / IP66',''],['Applications','Pompes / ventilateurs / compresseurs',''],['Mise en service','SmartStart','']]});

  const atv=await ensureModel(db,{category:'Variateur de fréquence',brand:'Schneider Electric',name:'Altivar Process ATV600',desc:'Variateur connecté orienté gestion des fluides et efficacité énergétique pour pompes, ventilateurs et compresseurs.',source:'https://www.se.com/fr/fr/product-range/62317-altivar-process-atv600/',aliases:'ATV600 Altivar VFD variateur process'});
  await ensureVariant(db,{modelId:atv,name:'ATV600 - gamme',source:'https://www.se.com/fr/fr/product-range/62317-altivar-process-atv600/',specs:[['Plage de puissance','0.75–2600','kW'],['Applications','Pompes / ventilateurs / compresseurs',''],['Connectivité','EcoStruxure / serveur Web / bus terrain',''],['Fonction','Gestion énergie et process','']]});

  const vrv=await ensureModel(db,{category:'DRV / VRV',brand:'Daikin',name:'VRV 5',desc:'Système DRV/VRV pour bâtiments commerciaux, architecture pompe à chaleur à débit de réfrigérant variable.',source:'https://www.daikin.fr/fr_fr/famille-produits/vrv/vrv5.html',aliases:'DRV VRF VRV5 R32'});
  await ensureVariant(db,{modelId:vrv,name:'VRV 5 - gamme extérieure',source:'https://www.daikin.fr/fr_fr/famille-produits/vrv/vrv5.html',specs:[['Puissance unité extérieure min','12.1','kW'],['Puissance unité extérieure max','87.5','kW'],['Application','Bâtiments commerciaux',''],['Technologie','Débit de réfrigérant variable','']]});

  const carrierSource='https://www.carrier.com/commercial/en/eu/products/air-treatment/rooftop-units/50ff-fc-100-280-r-454b/';
  const carrierImage='https://images.carriercms.com/image/upload/w_auto,c_lfill,q_auto,f_auto/v1720515408/carrier/commercial-hvac-europe/products/air-treatment/carrier-50fc-100-280-r454-b-rooftop.jpg';
  const rooftop=await ensureModel(db,{category:'Rooftop',brand:'Carrier',name:'50FF/FC 100-280 R-454B',desc:'Rooftop autonome compact air/air, versions froid seul ou pompe à chaleur, destiné aux moyennes et grandes surfaces.',source:carrierSource,image:carrierImage,aliases:'rooftop roof top PAC air air'});
  await ensureVariant(db,{modelId:rooftop,name:'50FF/FC 100-280 R-454B - gamme',source:carrierSource,specs:[['Fluide frigorigène','R-454B',''],['Puissance froid','97–273','kW'],['Puissance chauffage','97–299','kW'],['Débit d’air','10800–54000','m³/h'],['Applications','Hôtellerie / industrie / logistique / commerce','']]});

  await db.runAsync(`INSERT OR REPLACE INTO _meta(key,value) VALUES('equipment_catalog_peripheral_v1','1')`);
}
