import numpy as np, sys, time, base64
d=np.load('data.npz'); X=d['X']; y=d['y']; n=len(y)
rng=np.random.default_rng(1); idx=rng.permutation(n); X=X[idx]; y=y[idx]
nv=n//20; Xv,yv=X[:nv],y[:nv]; Xt,yt=X[nv:],y[nv:]
IN,H1,H2,OUT=X.shape[1],128,64,11
def he(i,o): return (rng.standard_normal((i,o))*np.sqrt(2/i)).astype(np.float32)
P={'W1':he(IN,H1),'b1':np.zeros(H1,np.float32),'W2':he(H1,H2),'b2':np.zeros(H2,np.float32),'W3':he(H2,OUT),'b3':np.zeros(OUT,np.float32)}
M={k:np.zeros_like(v) for k,v in P.items()}; V={k:np.zeros_like(v) for k,v in P.items()}
def fwd(x,P):
    h1=np.maximum(0,x@P['W1']+P['b1']); h2=np.maximum(0,h1@P['W2']+P['b2']); o=h2@P['W3']+P['b3']; return h1,h2,o
def softmax(o): o=o-o.max(1,keepdims=True); e=np.exp(o); return e/e.sum(1,keepdims=True)
def acc(x,y,P): return float((fwd(x,P)[2].argmax(1)==y).mean())
EPOCHS=int(sys.argv[1]) if len(sys.argv)>1 else 25; B=512; t=0; lr0=2e-3
for ep in range(EPOCHS):
    perm=rng.permutation(len(yt)); tl=0
    lr=lr0*(0.5*(1+np.cos(np.pi*ep/EPOCHS)))+2e-5
    for i in range(0,len(perm),B):
        b=perm[i:i+B]; x=Xt[b]; yb=yt[b]
        x=x*rng.uniform(.8,1.2,(len(b),1)).astype(np.float32)+rng.normal(0,.03,x.shape).astype(np.float32)   # extra jitter
        h1,h2,o=fwd(x,P); p=softmax(o); tl+=-np.log(p[np.arange(len(b)),yb]+1e-9).mean()
        do=p; do[np.arange(len(b)),yb]-=1; do/=len(b)
        g={}; g['W3']=h2.T@do; g['b3']=do.sum(0); dh2=do@P['W3'].T; dh2[h2<=0]=0
        g['W2']=h1.T@dh2; g['b2']=dh2.sum(0); dh1=dh2@P['W2'].T; dh1[h1<=0]=0
        g['W1']=x.T@dh1; g['b1']=dh1.sum(0)
        t+=1
        for k in P:
            gk=g[k]+1e-5*P[k]
            M[k]=.9*M[k]+.1*gk; V[k]=.999*V[k]+.001*gk*gk
            P[k]-=lr*(M[k]/(1-.9**t))/(np.sqrt(V[k]/(1-.999**t))+1e-8)
    print(f'epoch {ep+1} loss {tl/(len(perm)/B):.3f} val {acc(Xv,yv,P):.4f}',flush=True)
np.savez('mlp.npz',**P)
# int8 quantisation and Java export
def q(a): s=float(np.abs(a).max())/127.0; return np.round(a/s).astype(np.int8),s
Pq={}; blob=bytearray(); meta=[]
for k in ['W1','b1','W2','b2','W3','b3']:
    qa,s=q(P[k]); Pq[k]=qa.astype(np.float32)*s; blob+=qa.tobytes(); meta.append((k,qa.size,s))
print('quantised val acc',acc(Xv,yv,Pq))
b64=base64.b64encode(bytes(blob)).decode(); chunks=[b64[i:i+60000] for i in range(0,len(b64),60000)]
java='package com.metra.missiontools;\n\n/** Generated by tools: int8-quantised weights of the digit classifier (see docs/QA_OCR_SEVEN_SEGMENT.md). */\nfinal class SevenSegmentWeights {\n  private SevenSegmentWeights() {}\n'
java+='  static final int INPUTS = %d, HIDDEN1 = %d, HIDDEN2 = %d, OUTPUTS = %d;\n'%(IN,H1,H2,OUT)
java+='  static final float[] SCALES = {%s};\n'%', '.join('%.9ef'%m[2] for m in meta)
java+='  static final int[] SIZES = {%s};\n'%', '.join(str(m[1]) for m in meta)
for i,c in enumerate(chunks): java+='  private static final String CHUNK_%d = "%s";\n'%(i,c)
java+='  static String data() { return new StringBuilder()%s.toString(); }\n}\n'%''.join('.append(CHUNK_%d)'%i for i in range(len(chunks)))
open('SevenSegmentWeights.java','w').write(java); print('chunks',len(chunks),'bytes',len(blob))
